---
- hosts: localhost
  vars_files:
    - ../../../install/openshift/vars_common.yml
    - ../../../install/openshift/vars_env_{{ STAGE }}.yml
  tasks:
    - name: Create kafka topic 
      command: "{{KAFKA_TOPIC_CMD}} --create --topic opendj.data.playlist --partitions 1 --replication-factor {{KAFKA_NUM_BROKERS}} --config retention.ms=43200000" 
      register: topic_result
      failed_when: 'topic_result.rc != 0 and "already exists" not in topic_result.stderr'
      changed_when: '"already exists" not in topic_result.stderr'
      
    - name: Create ImageStreamTag
      k8s:
        state: present
        definition:
          kind: ImageStream
          apiVersion: image.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: service-playlist
            name: service-playlist
            namespace: "{{ NAMESPACE }}"
          spec:
            lookupPolicy:
              local: false
    - name: Create BuildConfig
      k8s:
        state: present
        definition:
          kind: BuildConfig
          apiVersion: build.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: service-playlist
            name: service-playlist
            namespace: "{{ NAMESPACE }}"
          spec:
            failedBuildsHistoryLimit: 5
            nodeSelector: null
            output:
              to:
                kind: ImageStreamTag
                name: service-playlist:latest
            postCommit: {}
            resources: {}
            runPolicy: Serial
            source:
              contextDir: components/service-playlist
              git:
                ref: "{{ GIT_REF }}"
                uri: https://github.com/opendj/opendj.git
              type: Git
            strategy:
              sourceStrategy:
                env:
                from:
                  kind: ImageStreamTag
                  name: "nodejs:10"
                  namespace: openshift
              type: Source
            successfulBuildsHistoryLimit: 2
            triggers:
            - imageChange:
              type: ImageChange
            - type: ConfigChange
            - github:
                secret: f8020eeb6055607a
              type: GitHub
            - generic:
                secret: 86c8f4979ce31b6c
              type: Generic
    - name: Create DeploymentConfig
      k8s:
        state: present
        wait: true
        definition:
          kind: DeploymentConfig
          apiVersion: apps.openshift.io/v1
          metadata:
            annotations:
              template.alpha.openshift.io/wait-for-ready: 'true'
            labels:
              app: service-playlist
            name: service-playlist
            namespace: "{{ NAMESPACE }}"
          spec:
            replicas: 1
            revisionHistoryLimit: 10
            selector:
              name: service-playlist
            strategy:
              activeDeadlineSeconds: 21600
              resources: {}
              rollingParams:
                intervalSeconds: 1
                maxSurge: 25%
                maxUnavailable: 25%
                timeoutSeconds: 600
                updatePeriodSeconds: 1
              type: Rolling
            template:
              metadata:
                labels:
                  name: service-playlist
                name: service-playlist
              spec:
                containers:
                  - env:
                      - name: LOG_LEVEL
                        value: "info"
                      - name: COMPRESS_RESULT
                        value: "true"
                      - name: KAFKA_HOST
                        value: "backend-eventstore-kafka-bootstrap:9092"
                      - name: SPOTIFY_PROVIDER_URL
                        value: "http://provider-spotify:8080/api/provider-spotify/v1/" 
                      - name: DEFAULT_AUTOFILL_EMPTY_PLAYLIST
                        value: "true"
                      - name: DEFAULT_IS_PLAYING
                        value: "true"
                      - name: DEFAULT_ALLOW_DUPLICATE_TRACKS
                        value: "false"
                      - name: MOCKUP_AUTOSKIP_SECONDS
                        value: "0"
                      - name: MOCKUP_NO_ACTUAL_PLAYING
                        value: "false"
                      - name: INTERNAL_POLL_INTERVAL
                        value: "100"
                    imagePullPolicy: IfNotPresent
                    name: service-playlist
                    ports:
                      - containerPort: 8081
                        protocol: TCP
                    resources:
                      limits:
                        memory: 256Mi
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                dnsPolicy: ClusterFirst
                restartPolicy: Always
                schedulerName: default-scheduler
                securityContext: {}
                terminationGracePeriodSeconds: 30
            test: false
            triggers:
              - imageChangeParams:
                  automatic: true
                  containerNames:
                    - service-playlist
                  from:
                    kind: ImageStreamTag
                    name: 'service-playlist:latest'
                    namespace: "{{ NAMESPACE }}"
                type: ImageChange
              - type: ConfigChange
    - name: Create Service
      k8s:
        state: present
        wait: true
        definition:
          kind: Service
          apiVersion: v1
          metadata:
            annotations:
            labels:
              app: service-playlist
            name: service-playlist
            namespace: "{{ NAMESPACE }}"
          spec:
            ports:
              - name: web
                port: 8081
                protocol: TCP
                targetPort: 8081
            selector:
              name: service-playlist
            sessionAffinity: None
            type: ClusterIP
    - name: Create Route
      k8s:
        state: present
        wait: true
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: service-playlist
            name: service-playlist
            namespace: "{{ NAMESPACE }}"
          spec:
            host: "{{DNS_BASENAME}}"
            path: /api/service-playlist
            to:
              kind: Service
              name: service-playlist
              weight: 100
            wildcardPolicy: None
