apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    application: backend-datagrid
  name: backend-datagrid
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      application: backend-datagrid
      deploymentConfig: backend-datagrid
  serviceName: backend-datagrid-ping
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: backend-datagrid
        deploymentConfig: backend-datagrid
      name: backend-datagrid
    spec:
      containers:
      - env:
        - name: CACHE_CONTAINER_START
          value: EAGER
        - name: SERVICE_NAME
          value: backend-datagrid
        - name: SERVICE_PROFILE
          value: datagrid-service
        - name: JGROUPS_PING_PROTOCOL
          value: openshift.DNS_PING
        - name: OPENSHIFT_DNS_PING_SERVICE_NAME
          value: backend-datagrid-ping
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: application-user
              name: backend-datagrid
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: application-password
              name: backend-datagrid
        - name: USER_CONFIG_MAP
          value: "false"
        image: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /opt/datagrid/bin/livenessProbe.sh
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: backend-datagrid
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        - containerPort: 11222
          name: hotrod
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /opt/datagrid/bin/readinessProbe.sh
          failureThreshold: 5
          initialDelaySeconds: 17
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            memory: "512"
          requests:
            cpu: 500m
            memory: "512"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/datagrid/standalone/data
          name: srv-data
        - mountPath: /var/run/secrets/java.io/keystores
          name: keystore-volume
        - mountPath: /var/run/secrets/openshift.io/serviceaccount
          name: service-certs
        - mountPath: /opt/datagrid/standalone/configuration/user
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: keystore-volume
      - name: service-certs
        secret:
          defaultMode: 420
          secretName: backend-datagrid-certs
      - configMap:
          defaultMode: 420
          name: backend-datagrid-config
        name: config-volume
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: srv-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: "1"
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: backend-datagrid-5f5bdbbdd5
  observedGeneration: 1
  replicas: 1
  updateRevision: backend-datagrid-5f5bdbbdd5
  updatedReplicas: 1
