apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: backend-datagrid
  namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
spec:
  service:
    type: DataGrid
    container:
      storage: 2Gi
  replicas: 1
  container:
    cpu: "{{ ENV.BACKEND_DATAGRID.LIMIT_CPU}}"
    extraJvmOpts: '-XX:NativeMemoryTracking=summary'
    memory: "{{ ENV.BACKEND_DATAGRID.LIMIT_MEMORY}}"
    storage: "{{ENV.BACKEND_DATAGRID.STORAGE_SIZE}}"
  security:
    endpointEncryption:
      type: None
#    endpointSecretName: connect-secret 
  logging:
    categories:
      org.infinispan: info
      org.jgroups: info
      org.jgroups.protocols.TCP: error
      org.jgroups.protocols.relay.RELAY2: fatal
