---
- name: Install OpenDJ
  gather_facts: false
  hosts: localhost
  vars_files:
    - vars_secrets.yml
    - vars_common.yml
    - vars_env_{{ STAGE }}.yml


  tasks:
    - name: "Combine env facts"
      tags: always
      set_fact:
        ENV: "{{ common | combine( specific, recursive=True) }}"

    - name: Create OpenShift Project
      tags: prj
      k8s:
        state: present
        wait: true
        definition:
          kind: Project
          apiVersion: project.openshift.io/v1
          metadata:
            name: "{{ENV.COMMON.NAMESPACE|mandatory}}"
            annotations:
              openshift.io/description: "OpenDJ stage {{ STAGE }} built from {{ENV.COMMON.GIT.REF}} "
              openshift.io/display-name: ""
    - name: Grant access to developer group
      tags: prj
      k8s:
        state: present
        definition:
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            creationTimestamp: null
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
            name: admin-0
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: opendj-developer
    - name: Create quay secret 
      when:
      tags: prj,quay
      k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: opendj-quay-secret
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          data:
            .dockerconfigjson: "{{ENV.COMMON.QUAY_SECRET}}" 
          type: kubernetes.io/dockerconfigjson

    - name: Grant access to images from other namespace
      when: not ENV.COMMON.CONTAINER_IMAGE_BUILD and not ENV.COMMON.CONTAINER_IMAGE_FROM_EXTERNAL_REGISTRY
      tags: prj
      k8s:
        state: present
        definition:
          kind: RoleBinding
          apiVersion: authorization.openshift.io/v1
          metadata:
            name: system:image-puller
            namespace: "{{ENV.COMMON.CONTAINER_IMAGE_FROM_NAMESPACE|mandatory}}"
          roleRef:
            name: system:image-puller
          groupNames:
          - "system:serviceaccounts:{{ENV.COMMON.NAMESPACE|mandatory}}"
          subjects:
          - kind: SystemGroup
            name: "system:serviceaccounts:{{ENV.COMMON.NAMESPACE|mandatory}}"
          userNames: null

- import_playbook: ../../components/backend-eventstore/openshift/install.yml
- import_playbook: ../../components/backend-datagrid/openshift/install.yml
- import_playbook: ../../components/provider-spotify/openshift/install.yml
- import_playbook: ../../components/service-eventactivity/openshift/install.yml
- import_playbook: ../../components/service-playlist/openshift/install.yml
- import_playbook: ../../components/service-web/openshift/install.yml
- import_playbook: ../../components/service-housekeeping/openshift/install.yml
- import_playbook: ../../components/frontend-web/openshift/install.yml
