---
- hosts: localhost
  vars_files:
    - ../../../install/openshift/vars_common.yml
    - ../../../install/openshift/vars_env_{{ STAGE }}.yml
  tasks:
    - name: "Combine env facts"
      set_fact:
        ENV: "{{ common | combine( specific, recursive=True) }}"
    - name: Create ImageStream
      k8s:
        state: present
        wait: true
        definition:
          kind: ImageStream
          apiVersion: image.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: service-web
            name: service-web
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            lookupPolicy:
              local: false
    - name: Create BuildConfig
      k8s:
        state: present
        wait: true
        definition:
          kind: BuildConfig
          apiVersion: build.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: service-web
            name: service-web
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            failedBuildsHistoryLimit: 5
            nodeSelector: null
            output:
              to:
                kind: ImageStreamTag
                name: service-web:latest
            postCommit: {}
            resources:
              limits:
                  memory: 256Mi
            runPolicy: Serial
            source:
              contextDir: components/service-web
              git:
                ref: "{{ENV.COMMON.GIT.REF | default('master')}}"
                uri: https://github.com/opendj/opendj.git
              type: Git
            strategy:
              sourceStrategy:
                env:
                - name: NPM_MIRROR
                from:
                  kind: ImageStreamTag
                  name: nodejs:10
                  namespace: openshift
              type: Source
            successfulBuildsHistoryLimit: 2
            triggers:
            - imageChange:
              type: ImageChange
            - type: ConfigChange
            - github:
                secret: f8020eeb6055607a
              type: GitHub
            - generic:
                secret: 86c8f4979ce31b6c
              type: Generic
    - name: Create DeploymentConfig
      k8s:
        state: present
        wait: true
        definition:
          kind: DeploymentConfig
          apiVersion: apps.openshift.io/v1
          metadata:
            annotations:
              template.alpha.openshift.io/wait-for-ready: 'true'
            labels:
              app: service-web
              template: opendj-nodejs-service-web
            name: service-web
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            replicas: "{{ENV.SERVICE_WEB.REPLICAS | default('1')}}"
            revisionHistoryLimit: 10
            selector:
              name: service-web
            strategy:
              activeDeadlineSeconds: 21600
              resources: {}
              rollingParams:
                intervalSeconds: 1
                maxSurge: 25%
                maxUnavailable: 25%
                timeoutSeconds: 600
                updatePeriodSeconds: 1
              type: Rolling
            template:
              metadata:
                labels:
                  name: service-web
                name: service-web
              spec:
                containers:
                  - env:
                      - name: LOG_LEVEL
                        value: "{{ENV.SERVICE_WEB.LOG_LEVEL | default('info')}}"
                      - name: KAFKA_HOST
                        value: "{{ENV.SERVICE_WEB.KAFKA_HOST | default('backend-eventstore-kafka-bootstrap:9092')}}"
                      - name: PORT
                        value: "{{ENV.SERVICE_WEB.PORT | default('8080')}}" 
                    imagePullPolicy: IfNotPresent
                    name: service-web
                    ports:
                      - containerPort: "{{ENV.SERVICE_WEB.PORT | default('8080')}}"
                        protocol: TCP
                    resources:
                      limits:
                        memory: 512Mi
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                dnsPolicy: ClusterFirst
                restartPolicy: Always
                schedulerName: default-scheduler
                securityContext: {}
                terminationGracePeriodSeconds: 30
            test: false
            triggers:
              - imageChangeParams:
                  automatic: true
                  containerNames:
                    - service-web
                  from:
                    kind: ImageStreamTag
                    name: 'service-web:latest'
                    namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
                type: ImageChange
              - type: ConfigChange
    - name: Create Service
      k8s:
        state: present
        wait: true
        definition:
          kind: Service
          apiVersion: v1
          metadata:
            annotations:
            labels:
              app: service-web
            name: service-web
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            ports:
              - name: web
# TODO: Find out why this does fail:
#                port: "{{ (ENV.SERVICE_WEB.PORT | default('8080')) | int }}"
                port: "8080"
                protocol: TCP
                targetPort: 8080
            selector:
              name: service-web
            sessionAffinity: None
            type: ClusterIP

    - name: Create Route with Let's Encrypt Certs
      when: ENV.FRONTEND_WEB.USE_ACME_CERTS|bool
      k8s:
        state: present
        wait: true
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            annotations:
              kubernetes.io/tls-acme: "true"
            labels:
              app: service-web
            name: service-web
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            host: "{{ENV.COMMON.DNS_BASENAME|mandatory}}"
            path: /api/service-web
            port:
              targetPort: web
              tls:
                insecureEdgeTerminationPolicy: "{{ENV.SERVICE_WEB.INSECURE_EDGE_TERMINATION}}"
                termination: "edge"
            to:
              kind: Service
              name: service-web
              weight: 100
            wildcardPolicy: None

    - name: Create Route with custom certs
      when: not ENV.FRONTEND_WEB.USE_ACME_CERTS|bool
      k8s:
        state: present
        wait: true
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            labels:
              app: service-web
            name: service-web
            namespace: "{{ENV.COMMON.NAMESPACE|mandatory}}"
          spec:
            host: "{{ENV.COMMON.DNS_BASENAME|mandatory}}"
            path: /api/service-web
            port:
              targetPort: web
            tls:
              insecureEdgeTerminationPolicy: "{{ENV.FRONTEND_WEB.INSECURE_EDGE_TERMINATION}}"
              termination: "edge"
              certificate: "{{ENV.FRONTEND_WEB.TLS_CERT}}"
              key: "{{ENV.FRONTEND_WEB.TLS_KEY}}"
            to:
              kind: Service
              name: service-web
              weight: 100
            wildcardPolicy: None
