---
- hosts: localhost
  vars_files:
    - ../../../install/openshift/vars_common.yml
    - ../../../install/openshift/vars_env_{{ STAGE }}.yml
  tasks:
#    - name: Create kafka topic 
#      command: kafka-topics --bootstrap-server localhost:9092  --create --topic opendj-spotifyprovider-internal  --partitions 1 --replication-factor 1 --config retention.ms=43200000 
      
    # Create Secret Manually:
    #  oc create secret generic test  --from-literal=CLIENT_ID=<SECRET> --from-literal=CLIENT_SECRET=<SECRET>
    # - name: Create Spotify secret
    #   k8s:
    #     state: present
    #     wait: true
    #     definition:
    #       apiVersion: v1
    #       kind: Secret
    #       data:
    #         CLIENT_ID: <SECRET>
    #         CLIENT_SECRET: <SECRET>
    #       metadata:
    #         name: spotify-api-credentials
    #         namespace: "{{NAMESPACE}}"
    - name: Create ImageStreamTag
      k8s:
        state: present
        wait: true
        definition:
          kind: ImageStream
          apiVersion: image.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: provider-spotify
            name: provider-spotify
            namespace: "{{NAMESPACE}}"
          spec:
            lookupPolicy:
              local: false
    - name: Create BuildConfig
      k8s:
        state: present
        wait: true
        definition:
          kind: BuildConfig
          apiVersion: build.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: provider-spotify
            name: provider-spotify
            namespace: "{{NAMESPACE}}"
          spec:
            failedBuildsHistoryLimit: 5
            nodeSelector: null
            output:
              to:
                kind: ImageStreamTag
                name: provider-spotify:latest
            postCommit: {}
            resources: {}
            runPolicy: Serial
            source:
              contextDir: components/provider-spotify
              git:
                ref: master
                uri: https://github.com/opendj/opendj.git
              type: Git
            strategy:
              sourceStrategy:
                env:
                - name: NPM_MIRROR
                from:
                  kind: ImageStreamTag
                  name: nodejs:10
                  namespace: openshift
              type: Source
            successfulBuildsHistoryLimit: 2
            triggers:
            - imageChange:
              type: ImageChange
            - type: ConfigChange
            - github:
                secret: 1qTuy4R21UDqOMqivTxpwrUN0brGdIONGdyBeCxX
              type: GitHub
            - generic:
                secret: rEVLkWDcrlBoPuionusPj0CL4A1H1DsFCMYPCdSw
              type: Generic
    - name: Create DeploymentConfig
      k8s:
        state: present
        wait: true
        definition:
          kind: DeploymentConfig
          apiVersion: apps.openshift.io/v1
          metadata:
            annotations:
              template.alpha.openshift.io/wait-for-ready: 'true'
            labels:
              app: provider-spotify
              template: opendj-nodejs-provider-spotify
            name: provider-spotify
            namespace: "{{NAMESPACE}}"
          spec:
            replicas: 2
            revisionHistoryLimit: 10
            selector:
              name: provider-spotify
            strategy:
              activeDeadlineSeconds: 21600
              resources: {}
              rollingParams:
                intervalSeconds: 1
                maxSurge: 25%
                maxUnavailable: 25%
                timeoutSeconds: 600
                updatePeriodSeconds: 1
              type: Rolling
            template:
              metadata:
                labels:
                  name: provider-spotify
                name: provider-spotify
              spec:
                containers:
                  - env:
                      - name: LOG_LEVEL
                        value: "info"
                      - name: COMPRESS_RESULT
                        value: "true"
                      - name: MOCKUP_ENABLED
                        value: "false"
                      - name: MOCKUP_TRACKDURATION_MS
                        value: "20000"
                      - name: KAFKA_HOST
                        value: "opendj-kafka-kafka-bootstrap:9092"
                      - name: SPOTIFY_CALLBACK_URL
                        value: "http://{{DNS_BASENAME}}/api/provider-spotify/v1/auth_callback"
                      - name: SPOTIFY_REFRESH_TOKEN_INTERVAL
                        value: "60000"
                      - name: SPOTIFY_REFRESH_INITIAL_DELAY
                        value: "1000"
                      - name: SPOTIFY_REFRESH_TOKEN_OFFSET
                        value: "300000"
                      - name: SPOTIFY_REFRESH_TOKEN_OFFSET_RANDOM
                        value: "180000"
                      - name: SPOTIFY_TRACK_DETAIL_NUM_GENRES
                        value: "3"     
                      - name: SPOTIFY_SEARCH_LIMIT
                        value: "20"     
                    envFrom:
                      - prefix: SPOTIFY_
                        secretRef:
                          name: spotify-api-credentials
                    imagePullPolicy: IfNotPresent
                    name: provider-spotify
                    ports:
                      - containerPort: 8080
                        protocol: TCP
                    readinessProbe:
                      failureThreshold: 3
                      httpGet:
                        path: /api/provider-spotify/v1/ready
                        port: 8080
                        scheme: HTTP
                      initialDelaySeconds: 1
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 1
                    resources:
                      limits:
                        memory: 512Mi
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                dnsPolicy: ClusterFirst
                restartPolicy: Always
                schedulerName: default-scheduler
                securityContext: {}
                terminationGracePeriodSeconds: 30
            test: false
            triggers:
              - imageChangeParams:
                  automatic: true
                  containerNames:
                    - provider-spotify
                  from:
                    kind: ImageStreamTag
                    name: 'provider-spotify:latest'
                    namespace: "{{NAMESPACE}}"
                type: ImageChange
              - type: ConfigChange
    - name: Create Service
      k8s:
        state: present
        wait: true
        definition:
          kind: Service
          apiVersion: v1
          metadata:
            annotations:
            labels:
              app: provider-spotify
            name: provider-spotify
            namespace: "{{NAMESPACE}}"
          spec:
            ports:
              - name: web
                port: 8080
                protocol: TCP
                targetPort: 8080
            selector:
              name: provider-spotify
            sessionAffinity: None
            type: ClusterIP
    - name: Create Route
      k8s:
        state: present
        wait: true
        definition:
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            annotations:
            labels:
              app: provider-spotify
            name: provider-spotify
            namespace: "{{NAMESPACE}}"
          spec:
            host: "{{DNS_BASENAME}}"
            path: /api/provider-spotify
            to:
              kind: Service
              name: provider-spotify
              weight: 100
            wildcardPolicy: None
            
